// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250729123029_CreateCategoriaTable")]
    partial class CreateCategoriaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComprasTccApp.Backend.Models.Entities.Items.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CatMat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Especificacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkImagem")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecoSugerido")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Categorias.Categoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Gestores.Gestor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataUltimaSolicitacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ServidorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ServidorId")
                        .IsUnique();

                    b.ToTable("Gestores");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Itens.SolicitacaoItem", b =>
                {
                    b.Property<long>("SolicitacaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SolicitacaoId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("SolicitacaoItens");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Pessoas.Pessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Servidores.Servidor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("IdentificadorInterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsGestor")
                        .HasColumnType("boolean");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.ToTable("Servidores");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Solicitacoes.Solicitacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GestorId")
                        .HasColumnType("bigint");

                    b.Property<string>("JustificativaGeral")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("SolicitanteId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GestorId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("Solicitacoes");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Solicitantes.Solicitante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataUltimaSolicitacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ServidorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServidorId")
                        .IsUnique();

                    b.ToTable("Solicitantes");
                });

            modelBuilder.Entity("ComprasTccApp.Backend.Models.Entities.Items.Item", b =>
                {
                    b.HasOne("ComprasTccApp.Models.Entities.Categorias.Categoria", "Categoria")
                        .WithMany("Itens")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Gestores.Gestor", b =>
                {
                    b.HasOne("ComprasTccApp.Models.Entities.Servidores.Servidor", "Servidor")
                        .WithOne()
                        .HasForeignKey("ComprasTccApp.Models.Entities.Gestores.Gestor", "ServidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servidor");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Itens.SolicitacaoItem", b =>
                {
                    b.HasOne("ComprasTccApp.Backend.Models.Entities.Items.Item", "Item")
                        .WithMany("SolicitacoesItem")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComprasTccApp.Models.Entities.Solicitacoes.Solicitacao", "Solicitacao")
                        .WithMany("ItemSolicitacao")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Servidores.Servidor", b =>
                {
                    b.HasOne("ComprasTccApp.Models.Entities.Pessoas.Pessoa", "Pessoa")
                        .WithOne()
                        .HasForeignKey("ComprasTccApp.Models.Entities.Servidores.Servidor", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Solicitacoes.Solicitacao", b =>
                {
                    b.HasOne("ComprasTccApp.Models.Entities.Gestores.Gestor", "Gestor")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("GestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComprasTccApp.Models.Entities.Solicitantes.Solicitante", "Solicitante")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gestor");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Solicitantes.Solicitante", b =>
                {
                    b.HasOne("ComprasTccApp.Models.Entities.Servidores.Servidor", "Servidor")
                        .WithOne()
                        .HasForeignKey("ComprasTccApp.Models.Entities.Solicitantes.Solicitante", "ServidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servidor");
                });

            modelBuilder.Entity("ComprasTccApp.Backend.Models.Entities.Items.Item", b =>
                {
                    b.Navigation("SolicitacoesItem");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Categorias.Categoria", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Gestores.Gestor", b =>
                {
                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Solicitacoes.Solicitacao", b =>
                {
                    b.Navigation("ItemSolicitacao");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Solicitantes.Solicitante", b =>
                {
                    b.Navigation("Solicitacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
