// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250922193204_AumentaDetalhesHistoricoItem")]
    partial class AumentaDetalhesHistoricoItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComprasTccApp.Backend.Models.Entities.Items.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CatMat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Especificacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkImagem")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecoSugerido")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Categorias.Categoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Descricao = "Componentes discretos e integrados para montagem e prototipagem de circuitos. Inclui resistores, capacitores, transistores, MCUs, LEDs e PCBs.",
                            IsActive = true,
                            Nome = "Componentes Eletrônicos"
                        },
                        new
                        {
                            Id = 2L,
                            Descricao = "Equipamentos elétricos de uso doméstico, em cozinhas ou escritórios. Abrange linha branca, portáteis e aparelhos de climatização.",
                            IsActive = true,
                            Nome = "Eletrodomésticos"
                        },
                        new
                        {
                            Id = 3L,
                            Descricao = "Instrumentos manuais e elétricos para manutenção, montagem, reparos e medições. Inclui chaves de fenda, alicates, furadeiras e multímetros.",
                            IsActive = true,
                            Nome = "Ferramentas"
                        },
                        new
                        {
                            Id = 4L,
                            Descricao = "Substâncias e compostos químicos utilizados em análises e sínteses. Inclui ácidos, bases, solventes, sais e padrões analíticos.",
                            IsActive = true,
                            Nome = "Reagentes Químicos"
                        },
                        new
                        {
                            Id = 5L,
                            Descricao = "Utensílios, consumíveis e pequenos equipamentos para uso geral em laboratório que não são vidrarias ou reagentes.",
                            IsActive = true,
                            Nome = "Materiais de Laboratório"
                        },
                        new
                        {
                            Id = 6L,
                            Descricao = "Móveis para ambientes de escritório, laboratórios ou áreas comuns, como mesas, cadeiras, armários e bancadas de trabalho.",
                            IsActive = true,
                            Nome = "Mobiliário"
                        },
                        new
                        {
                            Id = 7L,
                            Descricao = "Categoria residual para itens que não se enquadram claramente em nenhuma outra classificação. Ideal para materiais de escritório ou de consumo geral.",
                            IsActive = true,
                            Nome = "Diversos"
                        });
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Centros.Centro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Centros");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Configuracoes.Configuracao", b =>
                {
                    b.Property<string>("Chave")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Chave");

                    b.ToTable("Configuracoes");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Departamentos.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Gestores.Gestor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataUltimaSolicitacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ServidorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("ServidorId")
                        .IsUnique();

                    b.ToTable("Gestores");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Historicos.HistoricoBase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataOcorrencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detalhes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("HistoricoBase");

                    b.HasDiscriminator().HasValue("HistoricoBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Itens.SolicitacaoItem", b =>
                {
                    b.Property<long>("SolicitacaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Justificativa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SolicitacaoId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("SolicitacaoItens");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Pessoas.Pessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Servidores.Servidor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("IdentificadorInterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsGestor")
                        .HasColumnType("boolean");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.ToTable("Servidores");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Solicitacoes.Solicitacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("GestorId")
                        .HasColumnType("bigint");

                    b.Property<long>("SolicitanteId")
                        .HasColumnType("bigint");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoSolicitacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("GestorId");

                    b.HasIndex("SolicitanteId");

                    b.HasIndex("StatusId");

                    b.ToTable("Solicitacoes");

                    b.HasDiscriminator<string>("TipoSolicitacao").HasValue("Solicitacao");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Solicitantes.Solicitante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataUltimaSolicitacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<long>("ServidorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("ServidorId")
                        .IsUnique();

                    b.ToTable("Solicitantes");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Status.StatusSolicitacao", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("StatusSolicitacoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Solicitação recém-criada, aguardando a análise do gestor.",
                            Nome = "Pendente"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Devolvida ao solicitante para correção ou mais informações.",
                            Nome = "Aguardando Ajustes"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "A solicitação foi aceita pelo gestor e seguirá para o próximo fluxo.",
                            Nome = "Aprovada"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "O pedido foi permanentemente negado pelo gestor.",
                            Nome = "Rejeitada"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Encerrada antecipadamente pelo solicitante ou gestor.",
                            Nome = "Cancelada"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Estado de arquivamento para solicitações de ciclos anteriores.",
                            Nome = "Encerrada"
                        });
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Historicos.HistoricoItem", b =>
                {
                    b.HasBaseType("ComprasTccApp.Models.Entities.Historicos.HistoricoBase");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.HasIndex("ItemId");

                    b.HasIndex("PessoaId");

                    b.HasDiscriminator().HasValue("HistoricoItem");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Historicos.HistoricoSolicitacao", b =>
                {
                    b.HasBaseType("ComprasTccApp.Models.Entities.Historicos.HistoricoBase");

                    b.Property<long>("SolicitacaoId")
                        .HasColumnType("bigint");

                    b.HasIndex("PessoaId");

                    b.HasIndex("SolicitacaoId");

                    b.HasDiscriminator().HasValue("HistoricoSolicitacao");
                });

            modelBuilder.Entity("SolicitacaoGeral", b =>
                {
                    b.HasBaseType("ComprasTccApp.Models.Entities.Solicitacoes.Solicitacao");

                    b.Property<string>("JustificativaGeral")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasDiscriminator().HasValue("GERAL");
                });

            modelBuilder.Entity("SolicitacaoPatrimonial", b =>
                {
                    b.HasBaseType("ComprasTccApp.Models.Entities.Solicitacoes.Solicitacao");

                    b.HasDiscriminator().HasValue("PATRIMONIAL");
                });

            modelBuilder.Entity("ComprasTccApp.Backend.Models.Entities.Items.Item", b =>
                {
                    b.HasOne("ComprasTccApp.Models.Entities.Categorias.Categoria", "Categoria")
                        .WithMany("Itens")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Departamentos.Departamento", b =>
                {
                    b.HasOne("ComprasTccApp.Models.Entities.Centros.Centro", "Centro")
                        .WithMany("Departamentos")
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Centro");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Gestores.Gestor", b =>
                {
                    b.HasOne("ComprasTccApp.Models.Entities.Centros.Centro", "Centro")
                        .WithMany("Gestores")
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComprasTccApp.Models.Entities.Servidores.Servidor", "Servidor")
                        .WithOne("Gestor")
                        .HasForeignKey("ComprasTccApp.Models.Entities.Gestores.Gestor", "ServidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Centro");

                    b.Navigation("Servidor");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Itens.SolicitacaoItem", b =>
                {
                    b.HasOne("ComprasTccApp.Backend.Models.Entities.Items.Item", "Item")
                        .WithMany("SolicitacoesItem")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComprasTccApp.Models.Entities.Solicitacoes.Solicitacao", "Solicitacao")
                        .WithMany("ItemSolicitacao")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Servidores.Servidor", b =>
                {
                    b.HasOne("ComprasTccApp.Models.Entities.Pessoas.Pessoa", "Pessoa")
                        .WithOne("Servidor")
                        .HasForeignKey("ComprasTccApp.Models.Entities.Servidores.Servidor", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Solicitacoes.Solicitacao", b =>
                {
                    b.HasOne("ComprasTccApp.Models.Entities.Gestores.Gestor", "Gestor")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("GestorId");

                    b.HasOne("ComprasTccApp.Models.Entities.Solicitantes.Solicitante", "Solicitante")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComprasTccApp.Models.Entities.Status.StatusSolicitacao", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gestor");

                    b.Navigation("Solicitante");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Solicitantes.Solicitante", b =>
                {
                    b.HasOne("ComprasTccApp.Models.Entities.Departamentos.Departamento", "Departamento")
                        .WithMany("Solicitantes")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComprasTccApp.Models.Entities.Servidores.Servidor", "Servidor")
                        .WithOne("Solicitante")
                        .HasForeignKey("ComprasTccApp.Models.Entities.Solicitantes.Solicitante", "ServidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Servidor");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Historicos.HistoricoItem", b =>
                {
                    b.HasOne("ComprasTccApp.Backend.Models.Entities.Items.Item", "Item")
                        .WithMany("Historico")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComprasTccApp.Models.Entities.Pessoas.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Historicos.HistoricoSolicitacao", b =>
                {
                    b.HasOne("ComprasTccApp.Models.Entities.Pessoas.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComprasTccApp.Models.Entities.Solicitacoes.Solicitacao", "Solicitacao")
                        .WithMany("Historico")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("ComprasTccApp.Backend.Models.Entities.Items.Item", b =>
                {
                    b.Navigation("Historico");

                    b.Navigation("SolicitacoesItem");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Categorias.Categoria", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Centros.Centro", b =>
                {
                    b.Navigation("Departamentos");

                    b.Navigation("Gestores");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Departamentos.Departamento", b =>
                {
                    b.Navigation("Solicitantes");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Gestores.Gestor", b =>
                {
                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Pessoas.Pessoa", b =>
                {
                    b.Navigation("Servidor");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Servidores.Servidor", b =>
                {
                    b.Navigation("Gestor");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Solicitacoes.Solicitacao", b =>
                {
                    b.Navigation("Historico");

                    b.Navigation("ItemSolicitacao");
                });

            modelBuilder.Entity("ComprasTccApp.Models.Entities.Solicitantes.Solicitante", b =>
                {
                    b.Navigation("Solicitacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
