using System.ComponentModel;

namespace ComprasTccApp.Backend.Enums
{
    public enum DepartamentoEnum
    {
        [Description("DEPARTAMENTO DE CIÊNCIA E ENGENHARIA DE MATERIAIS")]
        DEPARTAMENTO_DE_CIENCIA_E_ENGENHARIA_DE_MATERIAIS,

        [Description("DEPARTAMENTO DE COMPUTAÇÃO")]
        DEPARTAMENTO_DE_COMPUTACAO,

        [Description("DEPARTAMENTO DE ENGENHARIA AMBIENTAL")]
        DEPARTAMENTO_DE_ENGENHARIA_AMBIENTAL,

        [Description("DEPARTAMENTO DE ENGENHARIA CIVIL")]
        DEPARTAMENTO_DE_ENGENHARIA_CIVIL,

        [Description("DEPARTAMENTO DE ENGENHARIA DE PETRÓLEO")]
        DEPARTAMENTO_DE_ENGENHARIA_DE_PETROLEO,

        [Description("DEPARTAMENTO DE ENGENHARIA DE PRODUÇÃO")]
        DEPARTAMENTO_DE_ENGENHARIA_DE_PRODUCAO,

        [Description("DEPARTAMENTO DE ENGENHARIA ELÉTRICA")]
        DEPARTAMENTO_DE_ENGENHARIA_ELETRICA,

        [Description("DEPARTAMENTO DE ENGENHARIA MECÂNICA")]
        DEPARTAMENTO_DE_ENGENHARIA_MECANICA,

        [Description("DEPARTAMENTO DE ENGENHARIA QUÍMICA")]
        DEPARTAMENTO_DE_ENGENHARIA_QUIMICA,

        [Description("DEPARTAMENTO DE ESTATÍSTICA E CIÊNCIAS ATUARIAIS")]
        DEPARTAMENTO_DE_ESTATISTICA_E_CIENCIAS_ATUARIAIS,

        [Description("DEPARTAMENTO DE FÍSICA")]
        DEPARTAMENTO_DE_FISICA,

        [Description("DEPARTAMENTO DE GEOLOGIA")]
        DEPARTAMENTO_DE_GEOLOGIA,

        [Description("DEPARTAMENTO DE MATEMÁTICA")]
        DEPARTAMENTO_DE_MATEMATICA,

        [Description("DEPARTAMENTO DE QUÍMICA")]
        DEPARTAMENTO_DE_QUIMICA,

        [Description("DEPARTAMENTO DE TECNOLOGIA DE ALIMENTOS")]
        DEPARTAMENTO_DE_TECNOLOGIA_DE_ALIMENTOS
    }
}